//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataAnnexe
    {
        public int ID { get; set; }
        public string IdLigne { get; set; }
        public string LibelleLignes { get; set; }
        public string IdLieux { get; set; }
        public string LibelleLieux { get; set; }
        public string F5 { get; set; }
        public string Tunnels { get; set; }
        public string TypeStructIndiqueMaconnerie { get; set; }
        public string IdOuvrage { get; set; }
        public string TABLEAU_DES_VISITEURS_DE_NUIT { get; set; }
        public string F10 { get; set; }
        public string Pk_OA_Debut { get; set; }
        public string Pk_OA__fin { get; set; }
        public string Long_OP_a_controler { get; set; }
        public string Surface_developpe { get; set; }
        public string Long_OA { get; set; }
        public string Code_Pat { get; set; }
        public string Nature_lieu { get; set; }
        public string DateConstruction_Annee { get; set; }
        public string DateConstruction_Note { get; set; }
        public string HistoriqueConfortementMac_Annee { get; set; }
        public string HistoriqueConfortementMac_Note { get; set; }
        public string HistoriqueRefectionEnduit_Anne { get; set; }
        public string HistoriqueRefectionEnduit_Note { get; set; }
        public string LargeurOuvrage_NombreVoies { get; set; }
        public string LargeurOuvrage_Note { get; set; }
        public string AgressiviteChimiqueTerrainEncaissant_ZoneInfluenceSeine { get; set; }
        public string AgressiviteChimiqueTerrainEncaissant_TeneursSulfate { get; set; }
        public string AgressiviteChimiqueTerrainEncaissant_Note { get; set; }
        public string SolubiliteTerrain_Natureterrain { get; set; }
        public string SolubiliteTerrain_PresenceEauNappePhreatique { get; set; }
        public string SolubiliteTerrain_Note { get; set; }
        public string PourrissementBoisBlindage_Cas { get; set; }
        public string PourrissementBoisBlindage_Note { get; set; }
        public string Frequentation_Cas { get; set; }
        public string Frequentation_Note { get; set; }
        public string Correspondance_Cas { get; set; }
        public string Correspondance_Note { get; set; }
        public string PerimetreL2L6_Cas { get; set; }
        public string PerimetreL2L6_Note { get; set; }
        public string ImageRATP_Cas { get; set; }
        public string ImageRATP_Note { get; set; }
    }
}
