//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desordres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Desordres()
        {
            this.DesordresDocuments = new HashSet<DesordresDocuments>();
            this.DesordreNotesTypes = new HashSet<DesordreNotesTypes>();
            this.DesordresInfos = new HashSet<DesordresInfos>();
            this.Causes = new HashSet<Causes>();
        }
    
        public int Id { get; set; }
        public int IdStatut { get; set; }
        public Nullable<int> IdLocalisation { get; set; }
        public int IdFamilleDesordreType { get; set; }
        public Nullable<int> IdAncienneFamilleType { get; set; }
        public Nullable<int> IdObservationTravaux { get; set; }
        public Nullable<int> IdDesordreCommun { get; set; }
        public Nullable<System.DateTime> DateSaisie { get; set; }
        public Nullable<int> NotePrecedente { get; set; }
        public Nullable<int> Note { get; set; }
        public string CaractCommentaire { get; set; }
        public string EnvCommentaire { get; set; }
        public string AncienneCaractFamille { get; set; }
        public bool NouveauDesordre { get; set; }
        public bool Actif { get; set; }
        public string ConstatCommentaire { get; set; }
        public int Situation { get; set; }
        public Nullable<int> NumeroAffichage { get; set; }
        public string IdIdCapture { get; set; }
        public Nullable<System.DateTime> DatePvsr { get; set; }
        public Nullable<int> IdFrequenceSurveillance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesordresDocuments> DesordresDocuments { get; set; }
        public virtual FamillesDesordresTypes FamillesDesordresTypes { get; set; }
        public virtual FamillesDesordresTypes FamillesDesordresTypes1 { get; set; }
        public virtual Localisations Localisations { get; set; }
        public virtual StatutsDesordres StatutsDesordres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesordreNotesTypes> DesordreNotesTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesordresInfos> DesordresInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Causes> Causes { get; set; }
    }
}
