//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesordresDocuments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DesordresDocuments()
        {
            this.DocumentsLies = new HashSet<DocumentsLies>();
        }
    
        public int Id { get; set; }
        public int IdDesordre { get; set; }
        public int IdDocument { get; set; }
        public Nullable<int> IdNatureTravaux { get; set; }
        public Nullable<int> IdTypeSurveillance { get; set; }
        public Nullable<double> Sdm { get; set; }
        public Nullable<System.DateTime> AnneeIndicative { get; set; }
        public string DelaiDemande { get; set; }
        public string ContrainteExploitation { get; set; }
        public string Commentaire { get; set; }
        public Nullable<System.DateTime> SrrExtDatePreconisation { get; set; }
        public string SrrExtNaturePreconisation { get; set; }
        public string SrrExtRemarque { get; set; }
        public Nullable<int> NumDe { get; set; }
        public Nullable<int> NbDe { get; set; }
        public Nullable<int> NumSrr { get; set; }
        public Nullable<int> NbSrr { get; set; }
        public Nullable<int> PgeBilanAnnee { get; set; }
        public Nullable<int> PgeBilanEvaluation { get; set; }
        public Nullable<int> PgeBilanIdentification { get; set; }
        public Nullable<System.DateTime> PgeBilanMaj { get; set; }
        public Nullable<int> PgeIdTitreIII { get; set; }
        public string PgeTitreM { get; set; }
        public Nullable<System.DateTime> PgeTitreMaj { get; set; }
        public Nullable<int> PgeRattache { get; set; }
        public Nullable<int> IdPvsrFrequence { get; set; }
    
        public virtual Desordres Desordres { get; set; }
        public virtual Documents Documents { get; set; }
        public virtual NaturesTravaux NaturesTravaux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentsLies> DocumentsLies { get; set; }
        public virtual TypesSurveillances TypesSurveillances { get; set; }
    }
}
