//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentsLies
    {
        public int Id { get; set; }
        public int IdDesordreDocument { get; set; }
        public int IdProcesVerbal { get; set; }
        public int IdStatutDocument { get; set; }
        public string RaisonAnnulation { get; set; }
        public System.DateTime DateStatut { get; set; }
        public int Relance { get; set; }
    
        public virtual DesordresDocuments DesordresDocuments { get; set; }
        public virtual ProcesVerbaux ProcesVerbaux { get; set; }
        public virtual StatutsDocuments StatutsDocuments { get; set; }
    }
}
