//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentPgeTravauxAnnees
    {
        public int Id { get; set; }
        public int IdDocumentProgrammation { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string Commentaire { get; set; }
        public Nullable<bool> Actif { get; set; }
    
        public virtual ProgrammationDocumentPGE ProgrammationDocumentPGE { get; set; }
    }
}
