//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GpeOuvragesComposition
    {
        public int Id { get; set; }
        public int IdGroupeOuvrage { get; set; }
        public int IdOuvrage { get; set; }
        public Nullable<bool> Inspection { get; set; }
        public string CauseNonInspection { get; set; }
        public string CommentaireOp { get; set; }
        public bool Controle { get; set; }
    
        public virtual GroupesOuvrages GroupesOuvrages { get; set; }
        public virtual Ouvrages Ouvrages { get; set; }
    }
}
