//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupesOuvrages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupesOuvrages()
        {
            this.GpeOuvragesComposition = new HashSet<GpeOuvragesComposition>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdProcesVerbal { get; set; }
        public Nullable<int> IdLigne { get; set; }
        public Nullable<int> IdSecteur { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> IdTypeProcesVerbal { get; set; }
        public Nullable<int> IdLieu { get; set; }
        public Nullable<int> IdPlanificationGroupeOuvrage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GpeOuvragesComposition> GpeOuvragesComposition { get; set; }
        public virtual ProcesVerbaux ProcesVerbaux { get; set; }
        public virtual Secteurs Secteurs { get; set; }
        public virtual TypesProcesVerbaux TypesProcesVerbaux { get; set; }
        public virtual Lieux Lieux { get; set; }
    }
}
