//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LieuxTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LieuxTypes()
        {
            this.Lieux = new HashSet<Lieux>();
        }
    
        public int Id { get; set; }
        public string Libelle { get; set; }
        public string TypeType { get; set; }
        public string TypeTypeCodeMire { get; set; }
        public Nullable<decimal> TypePa { get; set; }
        public string TypeCodeSsfa { get; set; }
        public Nullable<decimal> TypeOrdreAffichage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lieux> Lieux { get; set; }
    }
}
