//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lignes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lignes()
        {
            this.Lieux = new HashSet<Lieux>();
            this.Lieux1 = new HashSet<Lieux>();
            this.PlanificationGroupeOuvrage = new HashSet<PlanificationGroupeOuvrage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdFamilleLigne { get; set; }
        public string Code { get; set; }
        public string Nom { get; set; }
        public string Commentaire { get; set; }
        public string StationDepart { get; set; }
        public string StationArrivee { get; set; }
        public string CheminIcone { get; set; }
        public bool Actif { get; set; }
        public Nullable<int> OrdreAffichage { get; set; }
    
        public virtual FamillesLignes FamillesLignes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lieux> Lieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lieux> Lieux1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanificationGroupeOuvrage> PlanificationGroupeOuvrage { get; set; }
    }
}
