//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localisations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Localisations()
        {
            this.Desordres = new HashSet<Desordres>();
            this.Localisations1 = new HashSet<Localisations>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdProcesVerbal { get; set; }
        public Nullable<int> IdOuvragePrincipal { get; set; }
        public Nullable<int> IdZoneOP { get; set; }
        public Nullable<int> IdOuvrageSecondaire { get; set; }
        public Nullable<int> IdZoneOS { get; set; }
        public Nullable<int> IdElementConstitutif { get; set; }
        public Nullable<int> IdInfosFixes { get; set; }
        public System.DateTime DateSaisie { get; set; }
        public string Position { get; set; }
        public string Commentaire { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public Nullable<bool> Atlas { get; set; }
        public Nullable<int> IdLocalisationApresMigration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desordres> Desordres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Localisations> Localisations1 { get; set; }
        public virtual Localisations Localisations2 { get; set; }
        public virtual Ouvrages Ouvrages { get; set; }
        public virtual Ouvrages Ouvrages1 { get; set; }
        public virtual ProcesVerbaux ProcesVerbaux { get; set; }
    }
}
