//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouvrages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ouvrages()
        {
            this.Localisations = new HashSet<Localisations>();
            this.Localisations1 = new HashSet<Localisations>();
            this.Ouvrages1 = new HashSet<Ouvrages>();
            this.GpeOuvragesComposition = new HashSet<GpeOuvragesComposition>();
            this.PlanificationComposition = new HashSet<PlanificationComposition>();
        }
    
        public int Id { get; set; }
        public int IdTypeOuvrage { get; set; }
        public int IdDescription { get; set; }
        public Nullable<int> IdOpParent { get; set; }
        public int IdLieuProprietaire { get; set; }
        public Nullable<int> IdLieuGestionnaire { get; set; }
        public string CodeMire { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Position { get; set; }
        public Nullable<float> Longueur { get; set; }
        public Nullable<int> CycleInspection { get; set; }
        public bool SoumisSrr { get; set; }
        public bool SoumisNq { get; set; }
        public Nullable<System.DateTime> DateHistorique { get; set; }
        public Nullable<int> IdTypeModification { get; set; }
        public Nullable<bool> Actif { get; set; }
    
        public virtual Descriptions Descriptions { get; set; }
        public virtual Lieux Lieux { get; set; }
        public virtual Lieux Lieux1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Localisations> Localisations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Localisations> Localisations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ouvrages> Ouvrages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GpeOuvragesComposition> GpeOuvragesComposition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanificationComposition> PlanificationComposition { get; set; }
        public virtual TypesOuvrages TypesOuvrages { get; set; }
    }
}
