//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametresProgrammation
    {
        public int Id { get; set; }
        public int IdProgrammation { get; set; }
        public Nullable<int> IdParametre { get; set; }
        public Nullable<int> IdCritere { get; set; }
        public Nullable<decimal> Valeur_New { get; set; }
        public Nullable<decimal> Valeur_Old { get; set; }
    
        public virtual ParametresHidalgo ParametresHidalgo { get; set; }
        public virtual Programmations Programmations { get; set; }
    }
}
