//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanificationGroupeOuvrage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanificationGroupeOuvrage()
        {
            this.PlanificationComposition = new HashSet<PlanificationComposition>();
            this.Planification = new HashSet<Planification>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdSecteur { get; set; }
        public Nullable<int> IdLigne { get; set; }
        public Nullable<int> IdLieu { get; set; }
        public int IdGroupe { get; set; }
        public Nullable<int> IdTypeProcesVerbal { get; set; }
        public Nullable<int> IdDocumentType { get; set; }
        public string Titre { get; set; }
        public Nullable<int> CycleInspection { get; set; }
    
        public virtual Lieux Lieux { get; set; }
        public virtual Lignes Lignes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanificationComposition> PlanificationComposition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planification> Planification { get; set; }
        public virtual Secteurs Secteurs { get; set; }
        public virtual TypesProcesVerbaux TypesProcesVerbaux { get; set; }
    }
}
