//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanificationComposition
    {
        public int Id { get; set; }
        public int IdPlanificationGroupeOuvrage { get; set; }
        public Nullable<int> IdOuvrage { get; set; }
    
        public virtual Ouvrages Ouvrages { get; set; }
        public virtual PlanificationGroupeOuvrage PlanificationGroupeOuvrage { get; set; }
    }
}
