//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planification
    {
        public int Id { get; set; }
        public int IdPlanificationGroupeOuvrage { get; set; }
        public Nullable<int> IdProcesVerbal { get; set; }
        public int IdTypeDocument { get; set; }
        public Nullable<int> IdUtilisateur { get; set; }
        public Nullable<int> IdPlanificationType { get; set; }
        public string Commentaires { get; set; }
        public string Raison { get; set; }
        public string Contraintes { get; set; }
        public Nullable<int> IdSurveillant { get; set; }
        public Nullable<int> NbJours { get; set; }
        public Nullable<int> NbNuits { get; set; }
        public Nullable<int> NbSurv { get; set; }
        public Nullable<System.DateTime> AnneeInspVis { get; set; }
        public string AnneeNivSurv { get; set; }
        public bool Actif { get; set; }
    
        public virtual PlanificationGroupeOuvrage GroupeOuvrage { get; set; }
        public virtual PlanificationsTypes PlanificationsTypes { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
