//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesVerbaux
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcesVerbaux()
        {
            this.DocumentsLies = new HashSet<DocumentsLies>();
            this.GroupeOuvrage = new HashSet<GroupesOuvrages>();
            this.Localisations = new HashSet<Localisations>();
            this.ProcesVerbaux1 = new HashSet<ProcesVerbaux>();
            this.ValidationsProcesVerbaux = new HashSet<ValidationsProcesVerbaux>();
            this.Planification = new HashSet<Planification>();
        }
    
        public int Id { get; set; }
        public int IdDocumentType { get; set; }
        public Nullable<int> IdTypeProvesVerbal { get; set; }
        public string NumeroAffaire { get; set; }
        public string Description { get; set; }
        public Nullable<int> Note { get; set; }
        public string Commentaire { get; set; }
        public Nullable<System.DateTime> DatePlanification { get; set; }
        public Nullable<System.DateTime> DateOuverture { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<System.DateTime> DatePremiereImpression { get; set; }
        public Nullable<int> IdPvAnterieur { get; set; }
        public bool Archive { get; set; }
        public Nullable<int> EtatSaisie { get; set; }
        public string CommentaireAccueil { get; set; }
        public Nullable<bool> ConformiteVitrail { get; set; }
        public string CommentaireVitrail { get; set; }
        public Nullable<int> IdFrequenceSurveillance { get; set; }
        public Nullable<System.DateTime> DatePvsr { get; set; }
        public Nullable<int> IdRedacteurPVSR { get; set; }
        public Nullable<System.DateTime> DateProchaineCreationPvsr { get; set; }
        public Nullable<int> FlagCreationService { get; set; }
        public Nullable<int> AncienneNotePV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentsLies> DocumentsLies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupesOuvrages> GroupeOuvrage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Localisations> Localisations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesVerbaux> ProcesVerbaux1 { get; set; }
        public virtual ProcesVerbaux ProcesVerbaux2 { get; set; }
        public virtual TypesProcesVerbaux TypesProcesVerbaux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidationsProcesVerbaux> ValidationsProcesVerbaux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planification> Planification { get; set; }
    }
}
