//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammationValeurParametresDocument
    {
        public int IDParametreHidalgo { get; set; }
        public int IDDocumentPge { get; set; }
        public Nullable<int> IDCritere { get; set; }
        public Nullable<double> Note { get; set; }
    
        public virtual ParametresHidalgo ParametresHidalgo { get; set; }
        public virtual ProgrammationDocumentPGE ProgrammationDocumentPGE { get; set; }
    }
}
