//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programmations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programmations()
        {
            this.ParametresProgrammation = new HashSet<ParametresProgrammation>();
            this.ProgrammationDetails = new HashSet<ProgrammationDetails>();
            this.ProgrammationDocumentPGE = new HashSet<ProgrammationDocumentPGE>();
        }
    
        public int IdProgrammation { get; set; }
        public int IdNatureTravaux { get; set; }
        public int IdTypeOuvrage { get; set; }
        public int AnneeProgrammation { get; set; }
        public System.DateTime DateCreation { get; set; }
        public int UserCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public Nullable<int> UserModification { get; set; }
        public Nullable<decimal> PrixUnitaire { get; set; }
        public Nullable<decimal> BudgetDisponible { get; set; }
    
        public virtual NatureTravaux NatureTravaux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParametresProgrammation> ParametresProgrammation { get; set; }
        public virtual TypeOuvrage TypeOuvrage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgrammationDetails> ProgrammationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgrammationDocumentPGE> ProgrammationDocumentPGE { get; set; }
    }
}
