//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Data.Contract.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammationDetails
    {
        public int IdProgrammationDetail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int IdProgrammation { get; set; }
        public Nullable<int> IdLigne { get; set; }
        public Nullable<int> IdLieu { get; set; }
        public Nullable<int> IdNatureTravauxExternes { get; set; }
        public Nullable<int> IdCategorie { get; set; }
        public System.DateTime DateCreation { get; set; }
        public int UserCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public Nullable<int> UserModification { get; set; }
    
        public virtual NatureTravauxExternes NatureTravauxExternes { get; set; }
        public virtual Programmations Programmations { get; set; }
        public virtual Categorie Categorie { get; set; }
    }
}
