//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratp.Hidalgo.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ratp.Hidalgo.Web.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limegreen.
        /// </summary>
        public static string B0_Color {
            get {
                return ResourceManager.GetString("B0_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yellow.
        /// </summary>
        public static string B1_Color {
            get {
                return ResourceManager.GetString("B1_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orange.
        /// </summary>
        public static string B2_Color {
            get {
                return ResourceManager.GetString("B2_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        public static string B3_Color {
            get {
                return ResourceManager.GetString("B3_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez renseigner ce champ..
        /// </summary>
        public static string MsgErrorRequired {
            get {
                return ResourceManager.GetString("MsgErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez renseigner une valeur max de {0} chiffre.
        /// </summary>
        public static string MsgErrValidationRangeEntier {
            get {
                return ResourceManager.GetString("MsgErrValidationRangeEntier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La somme des valeurs des coefficients de pondération des critères ne peut pas être égale à 0..
        /// </summary>
        public static string MsgErrValidationSommeCriteres {
            get {
                return ResourceManager.GetString("MsgErrValidationSommeCriteres", resourceCulture);
            }
        }
    }
}
